---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - metalmachines
  - serverbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - metalmachines/status
  - serverbindings/status
  verbs:
  - get
- apiGroups:
  - metal.sidero.dev
  resources:
  - environments
  - serverclasses
  - servers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.sidero.dev
  resources:
  - environments/status
  - serverclasses/status
  - servers/status
  verbs:
  - get
  - patch
  - update
