# commit to be tagged for new release
commit = "HEAD"

project_name = "Sidero"
github_repo = "talos-systems/sidero"
match_deps = "^github.com/(talos-systems/[a-zA-Z0-9-]+)$"

# previous release
previous = "v0.6.3"

pre_release = false

preface = """\
"""

[notes]

[notes.patches]
    title = "Patches"
        description = """\
Sidero Metal now supports Talos Linux machine configuration strategic merge patches via 'strategicPatches' field on the `Server` and `ServerClass` CRDs.
"""
