# commit to be tagged for new release
commit = "HEAD"

project_name = "Sidero"
github_repo = "talos-systems/sidero"
match_deps = "^github.com/(talos-systems/[a-zA-Z0-9-]+)$"

# previous release
previous = "v0.6.6"

pre_release = false

preface = """\
"""

[notes]

[notes.talos]
    title = "Talos Linux"
        description = """\
Sidero Metal now supports Talos Linux v1.9.x.
"""

[notes.capi]
    title = "Cluster API"
        description = """\
Sidero Metal is now built and tested with Cluster API 1.9.0.
"""
